# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false


# Starship modules
[character]
success_symbol = '[➜](bold #E6B450)'
error_symbol = '[➜](bold #FF8F40)'

[git_branch]
style = "bold #D2A6FF"

[git_status]
style = 'bold #73B8FF'

[git_metrics]
added_style = 'bold #7FD962'
deleted_style = 'bold #F26D78'

[directory]
truncation_length = 4
style = "bold #FFB454"

[package]
disabled = true

[java]
format = 'using [(${version} )]($style)'
style = 'bold #F07178'
version_format = '${raw}'

[nodejs]
format = 'using [(${version} )]($style)'
detect_files = ['package.json']
style = 'bold #AAD94C'
version_format = '${raw}'

[python]
format = 'using [(${version} )]($style)'
style = 'bold #AAD94C'
version_format = '${raw}'
disabled = true


[docker_context]
disabled = true
